In [1]:
# import packages for alpaca, panadas and OS/dotenv to read .env file with api keys
import os
import pandas as pd
import numpy as np
import alpaca_trade_api as tradeapi
# Load .env enviroment variables
from dotenv import load_dotenv
load_dotenv()
import pathlib as Path

In [2]:
#helpful maybe?
from datetime import datetime, timedelta

days = 90
startdate = datetime.now() - timedelta(days=days)

# for fixed dates
start = pd.to_datetime('2002-01-01')
end = pd.to_datetime('2020-01-01')

In [3]:
# storing alpaca key and secret key in variables 
alpaca_api_key = os.getenv('ALPACA_API_KEY')
alpaca_secret_key = os.getenv('ALPACA_SECRET_KEY')

api = tradeapi.REST(alpaca_api_key,alpaca_secret_key,api_version='V2')

In [4]:
# set time frame
timeframe = '1D'

# start and 'end' date for covid stock market 


start_date_covid = pd.Timestamp('2019-12-01',tz='America/New_York').isoformat()
end_date_covid = pd.Timestamp('2020-11-20',tz='America/New_York').isoformat()

# start and end date for 2008 recession 
start_date_2008 = pd.Timestamp('2007-07-01',tz='America/New_York').isoformat()
end_date_2008 = pd.Timestamp('2009-07-01',tz='America/New_York').isoformat()

# set tickers (per industry)
tickers_travel_airline = ['EXPE','BKNG','DAL','AAP','LUV']
# financeind_tickers
# techind_tickers etc

# get stock data from covid
tra_air_covid_ticker = api.get_barset(tickers_travel_airline,timeframe,start=start_date_covid,end = end_date_covid).df

# get stock data from 2008 recession
tra_air_ticker2008 = api.get_barset(tickers_travel_airline,timeframe,start=start_date_2008,end = end_date_2008).df

In [5]:

covid_sp500_df = pd.read_csv("Covid_SP500_data.csv", index_col="Date", parse_dates=True, infer_datetime_format=True)


covid_sp500_df = covid_sp500_df[['Adj Close']]
covid_sp500_df.head()


Adj Close
Date                   
2019-12-02  3113.870117
2019-12-03  3093.199951
2019-12-04  3112.760010
2019-12-05  3117.429932
2019-12-06  3145.909912

In [6]:

sp500_2008_df = pd.read_csv("S&P_Jul_2007_2009.csv", index_col="Date", parse_dates=True, infer_datetime_format=True)


sp500_2008_df = sp500_2008_df[['Adj Close']]
sp500_2008_df.head()

Adj Close
Date                   
2007-07-02  1519.430054
2007-07-03  1524.869995
2007-07-05  1525.400024
2007-07-06  1530.439941
2007-07-09  1531.849976

In [24]:
#ticker2008=ticker2008.reset_index()


In [8]:
tra_air_covid_ticker.tail()

AAP                                        BKNG  \
                             open    high       low   close   volume     open   
2020-11-16 00:00:00-05:00  155.50  156.06  150.3200  151.06  2025846  2117.87   
2020-11-17 00:00:00-05:00  149.92  150.70  147.6500  149.31  1643720  2080.00   
2020-11-18 00:00:00-05:00  148.93  151.83  147.9800  148.11  1583893  2076.00   
2020-11-19 00:00:00-05:00  147.54  147.54  144.0718  146.08  3001601  2022.84   
2020-11-20 00:00:00-05:00  145.91  147.09  143.8801  144.31  2527183  2017.60   

                                                                 ...    EXPE  \
                               high      low      close  volume  ...    open   
2020-11-16 00:00:00-05:00  2121.987  2060.78  2080.9312  523837  ...  128.77   
2020-11-17 00:00:00-05:00  2091.520  2057.96  2082.3700  241166  ...  122.58   
2020-11-18 00:00:00-05:00  2103.510  2044.02  2044.5900  288553  ...  123.10   
2020-11-19 00:00:00-05:00  2054.975  2000.00  2008.4700  304049  ...  121.61   
2020-11-20 00:00:00-05:00  2036.520  1987.84  1990.3000  249860  ...  123.45   

                                                              LUV         \
                             high     low   close   volume   open   high   
2020-11-16 00:00:00-05:00  128.98  122.32  123.68  2886547  46.06  46.20   
2020-11-17 00:00:00-05:00  123.78  121.13  123.04  1838484  44.86  46.24   
2020-11-18 00:00:00-05:00  126.08  122.01  122.40  1837959  46.82  47.28   
2020-11-19 00:00:00-05:00  124.16  120.03  123.97  1931119  45.53  46.46   
2020-11-20 00:00:00-05:00  123.66  119.77  119.83  2803234  46.05  46.05   

                                                    
                              low  close    volume  
2020-11-16 00:00:00-05:00  44.540  45.59  26155085  
2020-11-17 00:00:00-05:00  44.430  45.65  15798296  
2020-11-18 00:00:00-05:00  45.600  45.60  21577612  
2020-11-19 00:00:00-05:00  45.410  46.07  12527225  
2020-11-20 00:00:00-05:00  45.035  45.55  12240889  

[5 rows x 25 columns]

In [7]:
# create new covid and 2008 dataframe to store ckosing prices of each stock

covid_travel_closingprices = pd.DataFrame()

# get closing prices for all tickers
for ticker in tickers_travel_airline:
    covid_travel_closingprices[ticker]=tra_air_covid_ticker[ticker]['close']
    
# drop time component on index
covid_travel_closingprices.index = covid_travel_closingprices.index.date
    
covid_travel_closingprices.head()

EXPE     BKNG    DAL     AAP    LUV
2019-12-02  100.74  1884.45  56.75  156.55  56.71
2019-12-03   99.39  1877.44  55.61  152.62  55.93
2019-12-04  105.56  1923.00  56.06  152.33  55.79
2019-12-05  105.70  1904.32  55.89  152.30  55.53
2019-12-06  107.59  1931.20  56.14  154.60  55.94

In [9]:
travel_closingprices2008 = pd.DataFrame()

# get closing prices for all tickers
for ticker in tickers_travel_airline:
    travel_closingprices2008[ticker]=tra_air_ticker2008[ticker]['close']
    
# drop time component on index
travel_closingprices2008.index = travel_closingprices2008.index.date
    
travel_closingprices2008.head()

EXPE    BKNG     DAL    AAP    LUV
2008-01-02  61.10  115.21  13.800  37.58  11.79
2008-01-03  61.10  111.40  13.660  37.91  11.61
2008-01-04  59.12  107.54  12.444  35.69  11.42
2008-01-07  58.28  105.18  13.380  37.25  11.88
2008-01-08  57.62  102.10  11.770  35.32  11.28

In [22]:
# calculate daily returns for each timeframe
travel_covid_dr = covid_travel_closingprices.pct_change().dropna()
travel_returns2008 = travel_closingprices2008.pct_change().dropna()

In [14]:
#Name of stocks in portfolio
print(covid_travel_closingprices.columns)

ta_covid_weights = np.full((1, len(covid_travel_closingprices.columns)), 1/len(covid_travel_closingprices.columns))[0]
print("Weights")
print(ta_covid_weights)

#expect returns
print('Expected returns')
ta_covid_exp_return = np.sum((travel_covid_dr.mean()*ta_covid_weights)*252)
print(ta_covid_exp_return)

#expected STD/volatility
print('Expected volatility')
ta_covid_exp_volat = np.sqrt(np.dot(ta_covid_weights.T, np.dot(travel_covid_dr.cov()*252, ta_covid_weights)))
print(ta_covid_exp_volat)

#Shape ratio
print('Shape ratio')
ta_covid_sharpe = ta_covid_exp_return/ta_covid_exp_volat
print(ta_covid_sharpe)

Index(['EXPE', 'BKNG', 'DAL', 'AAP', 'LUV'], dtype='object')
Weights
[0.2 0.2 0.2 0.2 0.2]
Expected returns
0.10434643694427442
Expected volatility
0.5472121330343592
Shape ratio
0.1906873598830137


In [28]:
# running 100k simulations on portfolio
number_ports = 100000
ta_all_weights = np.zeros((number_ports, len(covid_travel_closingprices.columns)))
ta_returns_array = np.zeros(number_ports)
ta_volatility_array = np.zeros(number_ports)
ta_sharpe_array = np.zeros(number_ports)

np.random.seed(4)

for index in range(number_ports):
    #weights
    ta_covid_weights = np.array(np.random.random(5))
    ta_covid_weights = ta_covid_weights/np.sum(ta_covid_weights)

    #save weights
    ta_all_weights[index,:] = ta_covid_weights

    #expected returns
    ta_returns_array[index] = np.sum((travel_covid_dr.mean()*ta_covid_weights)*252)

    #expected volatiltiy
    ta_volatility_array[index] = np.sqrt(np.dot(ta_covid_weights.T, np.dot(travel_covid_dr.cov()*252, ta_covid_weights)))

    #sharpe ratio
    ta_sharpe_array[index] = ta_returns_array[index]/ta_volatility_array[index]

In [29]:
ta_sharpe_array.max()

0.5630037112949381

In [30]:
ta_index_max_shape = ta_sharpe_array.argmax()
ta_index_max_shape

79869

In [36]:
ta_weights_array = ta_all_weights[index_max_shape,:]
ta_weights_array

array([0.61837201, 0.18266603, 0.02917101, 0.16262027, 0.00717068])

In [23]:
#Name of stocks in portfolio
print(travel_closingprices2008.columns)

ta_2008_weights = np.full((1, len(travel_closingprices2008.columns)), 1/len(travel_closingprices2008.columns))[0]
print("Weights")
print(ta_2008_weights)

#expect returns
print('Expected returns')
ta_2008_exp_return = np.sum((travel_returns2008.mean()*ta_2008_weights)*252)
print(ta_2008_exp_return)

#expected STD/volatility
print('Expected volatility')
ta_2008_exp_volat = np.sqrt(np.dot(ta_2008_weights.T, np.dot(travel_returns2008.cov()*252, ta_2008_weights)))
print(ta_2008_exp_volat)

#Shape ratio
print('Shape ratio')
ta_2008_sharpe = ta_2008_exp_return/ta_2008_exp_volat
print(ta_2008_sharpe)

Index(['EXPE', 'BKNG', 'DAL', 'AAP', 'LUV'], dtype='object')
Weights
[0.2 0.2 0.2 0.2 0.2]
Expected returns
0.0710814285487679
Expected volatility
0.5521139726131628
Shape ratio
0.12874412182024403


In [32]:
# running 10k simulations on portfolio
number_ports = 100000
ta_all_weights_2008 = np.zeros((number_ports, len(travel_closingprices2008.columns)))
ta_returns_array_2008 = np.zeros(number_ports)
ta_volatility_array_2008 = np.zeros(number_ports)
ta_sharpe_array_2008 = np.zeros(number_ports)

np.random.seed(4)

for index in range(number_ports):
    #weights
    ta_2008_weights = np.array(np.random.random(5))
    ta_2008_weights = ta_2008_weights/np.sum(ta_2008_weights)

    #save weights
    ta_all_weights_2008[index,:] = ta_2008_weights

    #expected returns
    ta_returns_array_2008[index] = np.sum((travel_returns2008.mean()*ta_2008_weights)*252)

    #expected volatiltiy
    ta_volatility_array_2008[index] = np.sqrt(np.dot(ta_2008_weights.T, np.dot(travel_returns2008.cov()*252, ta_2008_weights)))

    #sharpe ratio
    ta_sharpe_array_2008[index] = ta_returns_array_2008[index]/ta_volatility_array_2008[index]

In [33]:
ta_sharpe_array_2008.max()

0.42531087446964183

In [34]:
ta_index_max_2008_shape = ta_sharpe_array_2008.argmax()
ta_index_max_2008_shape

80547

In [35]:
ta_weights_2008_array = ta_all_weights_2008[ta_index_max_2008_shape,:]
ta_weights_2008_array

array([0.00441766, 0.40000322, 0.07261973, 0.51761735, 0.00534204])

In [ ]:
ta_weights_2008_array = np.array([0.00441766, 0.40000322, 0.07261973, 0.51761735, 0.00534204])
ta_weights_2008_array

In [ ]:
ta_weights_array = np.array([0.61837201, 0.18266603, 0.02917101, 0.16262027, 0.00717068])
ta_weights_array

In [37]:
#Name of stocks in portfolio
print(covid_travel_closingprices.columns)

#expect returns
print('Expected returns')
ta_covid_exp_return = np.sum((travel_covid_dr.mean()*ta_weights_array)*252)
print(ta_covid_exp_return)

#expected STD/volatility
print('Expected volatility')
ta_covid_exp_volat = np.sqrt(np.dot(ta_weights_array.T, np.dot(travel_covid_dr.cov()*252, ta_weights_array)))
print(ta_covid_exp_volat)

#Shape ratio
print('Shape ratio')
ta_covid_sharpe = ta_covid_exp_return/ta_covid_exp_volat
print(ta_covid_sharpe)

Index(['EXPE', 'BKNG', 'DAL', 'AAP', 'LUV'], dtype='object')
Expected returns
0.3048618629415235
Expected volatility
0.5953480238897848
Shape ratio
0.512073359964594


In [38]:
#Name of stocks in portfolio
print(travel_closingprices2008.columns)

#expect returns
print('Expected returns')
ta_2008_exp_return = np.sum((travel_returns2008.mean()*ta_weights_2008_array)*252)
print(ta_2008_exp_return)

#expected STD/volatility
print('Expected volatility')
ta_2008_exp_volat = np.sqrt(np.dot(ta_weights_2008_array.T, np.dot(travel_returns2008.cov()*252, ta_weights_2008_array)))
print(ta_2008_exp_volat)

#Shape ratio
print('Shape ratio')
ta_2008_sharpe = ta_2008_exp_return/ta_2008_exp_volat
print(ta_2008_sharpe)

Index(['EXPE', 'BKNG', 'DAL', 'AAP', 'LUV'], dtype='object')
Expected returns
0.2108208168107489
Expected volatility
0.4956864013261834
Shape ratio
0.42531087446964183


## volatility for 2008 & COVID
* standard deviation
* box & whisker plot?

## Industries
* Tech: AMD, AAPL, MSFT, GOOG, INTC
* Entertainment: IMAX, DIS, NFLX, CNK, SNE
* Fast Food/Restaurants: MCD, WEN, YUM, DPZ, CMG
* Energy: XOM, BP, RDS, COP, CVX
* Travel/Airlines: EXPE, BKNG, DAL, AAP, UAL